services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
    driver: local
